[package]
name = "vef2-2025-e"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
nalgebra = "0.33.2"
getrandom = { version = "0.2", features = ["js"] }
rayon = "1.10.0"
wasm-bindgen = "0.2.100"
wasm-bindgen-futures = "0.4.50"
wasm-bindgen-rayon = "1.3.0"
fastrand = "2.3.0"
